blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/huaweicloud/.github#readme
    about: Please check the documentation before opening an issue.
  - name: 💬 Discussions
    url: https://github.com/huaweicloud/.github/discussions
    about: Ask questions and discuss with the community.
