name: Org Secret Test GH
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test org secrets in .github repo
        env:
          T_SMTP: ${{ secrets.SMTP_PORT }}
          T_BOT: ${{ secrets.BOT_TOKEN }}
          T_FEISHU: ${{ secrets.FEISHU_APP_ID }}
        run: |
          echo "SMTP_PORT length: ${#T_SMTP}"
          echo "BOT length: ${#T_BOT}"
          echo "FEISHU length: ${#T_FEISHU}"
