name: Org Secret Retest
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Retest
        env:
          T_SMTP: ${{ secrets.SMTP_PORT }}
          T_BOT: ${{ secrets.BOT_TOKEN }}
        run: |
          echo "SMTP length: ${#T_SMTP}"
          echo "BOT length: ${#T_BOT}"
